### ISSUE TITLE
Implement Get Customer Details WS

### ISSUE THREAD

**Issue by naween1994** [Direct-Entry-Program-009/pos-back-end#3]
GET /customers/{customer-id}
GET /customers/{customer-id}/

**Success Response**
200 OK
Content type: "application/JSON"
Returns a customer Object

Failed Response
404 NOT FOUND: If there is no match found for this {customer-id}
501 NOT IMPLEMENTED: if the {customer-id} is not valid or invalid URL

**Comment by amithchalana** [comment]
Time : 51 min
